export const DASHBOARD_MENU_TYPE = {
  REPORTS: {
    type: "REPORTS",
    AGENTS_UNPROCESSED_MONEY: "REPORTS_AGENTS_UNPROCESSED_MONEY",
    AGENTS_VICTORY_AND_DEFEAT: "REPORTS_AGENTS_VICTORY_AND_DEFEAT",
    AGENTS_WINNING_AND_LOSING_DETAILS:
      "REPORTS_AGENTS_WINNING_AND_LOSING_DETAILS",
    DETAILS_OF_WINS_AND_LOSSES_BY_MATCH:
      "REPORTS_DETAILS_OF_WINS_AND_LOSSES_BY_MATCH",
    ANALYSIS_OF_WIN_LOSS_RATIO: "REPORTS_ANALYSIS_OF_WIN_LOSS_RATIO",
    CHART_OF_WINNING_AND_LOSING: "REPORTS_CHART_OF_WINNING_AND_LOSING",
    WIN_OR_LOSE_ON_PRODUCTS: "REPORTS_WIN_OR_LOSE_ON_PRODUCTS",
    COMMISSIONS_BY_BET_TYPE: "REPORTS_COMMISSIONS_BY_BET_TYPE",
    STATEMENTS: "REPORT_STATEMENTS",
    RESULT: "REPORTS_RESULT",
    BONUS_OPENING_SCHEDULE: "REPORTS_BONUS_OPENING_SCHEDULE",
    PROGRESSIVE_GAME_ACCUMULATION: "REPORTS_PROGRESSIVE_GAME_ACCUMULATION",
    MONITOR_AVAILABILITY_LIMITS: "REPORTS_MONITOR_AVAILABILITY_LIMITS",
  },

  MEMBER_INFORMATION: {
    type: "MEMBER_INFORMATION",
    CREATE_MEMBER: "MEMBER_INFORMATION_CREATE_MEMBER",
    SECOND_ACCOUNT: "MEMBER_INFORMATION_SECOND_ACCOUNT",
    MEMBER_LIST: "MEMBER_INFORMATION_MEMBER_LIST",
    LIST_OF_PROBLEM_ACCOUNTS: "MEMBER_INFORMATION_LIST_OF_PROBLEM_ACCOUNTS",
    LIMIT_BALANCE: "MEMBER_INFORMATION_LIMIT_BALANCE",
    POSITION_TAKING: "MEMBER_INFORMATION_POSITION_TAKING",
    MEMBERS_COMMISSION: "MEMBER_INFORMATION_MEMBERS_COMMISSION",
    INDIRECT_ACCOUNT_LOGIN: "MEMBERS_COMMISSION_INDIRECT_ACCOUNT_LOGIN",
    LIST_OF_INACTIVE_ACCOUNTS: "MEMBER_INFORMATION_LIST_OF_INACTIVE_ACCOUNTS",
  },

  LIST_OF_BETS: {
    type: "LIST_OF_BETS",
    BE_AVOID: "LIST_OF_BETS_BE_AVOID",
    ACCURACY_SCORE: "LIST_OF_BETS_ACCURACY_SCORE",
    SYNTHETIC_BETS: "LIST_OF_BET_SYNTHETIC_BETS",
    KEEP_THE_NET_CLEAN: "LIST_OF_BETS_KEEP_THE_NET_CLEAN",
    DOUBLE_CHANCE: "LIST_OF_BETS_DOUBLE_CHANCE",
    BOTH_ONE_NO_TEAM_SCORED: "LIST_OF_BETS_BOTH_ONE_NO_TEAM_SCORED",
    OVERWHELMING_WIN_BETS: "LIST_OF_BETS_OVERWHELMING_WIN_BETS",
    _3_WAY_HANDICAP: "LIST_OF_BETS_3_WAY_HANDICAP",
  },

  TOTAL_BET_PREDICTION: {
    type: "TOTAL_BET_PREDICTION",
    HANDICAP_OVER_UNDER_LIVE_BETS:
      "TOTAL_BET_PREDICTION_HANDICAP_OVER_UNDER_LIVE_BETS",
    MONEYLINE: "TOTAL_BET_PREDICTION_MONEYLINE",
    ODD_EVEN_1X2_DRAW_NO_DRAW: "TOTAL_BET_PREDICTION_ODD_EVEN_1X2_DRAW_NO_DRAW",
    TOTAL_GOALS: "TOTAL_BET_PREDICTION_TOTAL_GOALS",
    BET_WIN: "TOTAL_BET_PREDICTION_BET_WIN",
    H1_FULL_MATCH: "TOTAL_BET_PREDICTION_H1_FULL_MATCH",
    FIRST_LAST_GOALS: "TOTAL_BET_PREDICTION_FIRST_LAST_GOALS",
    HOUSE_TIE_GUEST_NOT_INCLUDED:
      "TOTAL_BET_PREDICTION_HOUSE_TIE_GUEST_NOT_INCLUDED",
    NUMBER_GAME: "TOTAL_BET_PREDICTIO_NUMBER_GAME",
    _1X2: "TOTAL_BET_PREDICTION_1X2",
    SCORE_MAP: "TOTAL_BET_PREDICTION_SCORE_MAP",
    PLOT_THREADS: "TOTAL_BET_PREDICTION_PLOT_THREADS",
  },

  TRANSFER: {
    type: "TRANSFER",
  },

  DIARY: {
    type: "DIARY",
    SETTINGS: "DIARY_SETTINGS",
    STATUS: "DIARY_STATUS",
    CREDIT: "DIARY_CREDIT",
    LOGIN: "DIARY_LOGIN",
  },

  NOTIFY: {
    type: "NOTIFY",
    COMMON: "NOTIFY_COMMON",
    SPECIAL: "NOTIFY_SPECIAL",
    SYSTEM: "NOTIFY_SYSTEM",
    MESSAGE_PERSONAL: "NOTIFY_MESSAGE_PERSONAL",
  },

  RISK_MANAGEMENT: {
    type: "RISK_MANAGEMENT",
    MEMBERS_WIN_LOSS_LIMIT: "RISK_MANAGEMENT_MEMBERS_WIN_LOSS_LIMIT",
    NEW_WIN_LOSS_LEVELS: "RISK_MANAGEMENT_NEW_WIN_LOSS_LEVELS",
  },

  SECURITY: {
    type: "SECURITY",
  },

  BACKUP_DOMAIN_NAME: {
    type: "BACKUP_DOMAIN_NAME",
  },
};
